[package]
name = "dedupe-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
hex.workspace = true
rayon.workspace = true
serde.workspace = true
sha2.workspace = true
walkdir.workspace = true
xxhash-rust.workspace = true
