[package]
name = "dedupe-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "dedupeforge"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
csv.workspace = true
dedupe-actions = { path = "../dedupe-actions" }
dedupe-core = { path = "../dedupe-core" }
dedupe-report-db = { path = "../dedupe-report-db" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
image.workspace = true
