[package]
name = "dedupe-gui"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "dedupeforge-gui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
dedupe-actions = { path = "../dedupe-actions" }
dedupe-core = { path = "../dedupe-core" }
eframe.workspace = true
serde.workspace = true
serde_json.workspace = true
